"use client";
import ContTitle from "@/components/title/ContTitle";
import React, { useEffect, useState } from "react";
import UnsplashCont from "./UnsplashCont";

export const metadata = {
  title: "Unsplash API",
  description: "Generated by create Unsplash API",
};

const Unsplash = () => {
  const [images, setImages] = useState([]);

  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.unsplash.com/photos?client_id=J2LaT4yhkYj1aMevZIbcACiyXSt2ATNj11PIfnxis9M&per_page=30"
      );
      if (!res.ok) {
        throw new Error("Failed to fetch data");
      }
      const data = await res.json();

      setImages(data);
    };
    getData();
  }, []);

  console.log(images);

  return (
    <>
      <ContTitle title="Unsplash" />
      <UnsplashCont images={images} />
    </>
  );
};

export default Unsplash;
