"use client";
import React, { useEffect, useState } from "react";
import styles from "./page.module.scss";
import MovieCont from "./MovieCont";
import ContTitle from "@/components/title/ContTitle";

export const metadata = {
  title: "Movie API",
  description: "Generated by create Movie API",
};

const Movie = () => {
  const [movies, setMovies] = useState([]);

  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.themoviedb.org/3/movie/popular?api_key=9be29262d25a4b248a7a8c73a358aa0d"
      );
      if (!res.ok) {
        throw new Error("Failed to fetch data");
      }
      const data = await res.json();

      setMovies(data.results);
    };
    getData();
  }, []);

  console.log(movies);

  return (
    <>
      <ContTitle title="Movie" />
      <MovieCont movies={movies} />
    </>
  );
};

export default Movie;
